# Generated by Django 4.0.7 on 2023-06-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_rename_album_name_album_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Album',
            new_name='album',
        ),
    ]
